spring:
  cache:
    cache-names: productNameCache
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=3600s
  application:
    name: MyRetailRestful
  data:
    mongodb:
      uri: mongodb+srv://${MONGOUSER:replaceuser}:${MONGOPASSWORD:replacepassword}@myretailrestful.vfytq.mongodb.net/?retryWrites=true&w=majority&appName=MyRetailRestful
      database: myRetailDB
server:
  port: ${PORT:8080}
external:
  api:
    url: https://redsky-uat.perf.target.com
logging:
  level:
    com.egraika.retailrestful: INFO



redskykey: ${REDSKYKEY:testkey}